<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PriceContent extends Model
{
    use HasFactory;

    protected $fillable = [
       'price_main_title',
       'price_desc_heading',
       'xpirix_plan_title',
       'month_price_free',
       'button_free_text',
       'free_feature_1',
       'free_feature_2',
       'free_feature_3',
       'free_feature_4',
       'free_feature_5',
       'free_feature_6',
       'free_feature_7',
       'basic_plan_title',
       'month_price_basic',
       'year_price_basic',
       'button_basic_text',
       'basic_feature_1',
       'basic_feature_2',
       'basic_feature_3',
       'basic_feature_4',
       'basic_feature_5',
       'basic_feature_6',
       'basic_feature_7',
       'family_plan_title',
       'month_price_family',
       'year_price_family',
       'button_family_text',
       'family_feature_1',
       'family_feature_2',
       'family_feature_3',
       'family_feature_4',
       'family_feature_5',
       'family_feature_6',
       'family_feature_7',
       'premium_plan_title',
       'month_price_premium',
       'year_price_premium',
       'button_premium_text',
       'premium_feature_1',
       'premium_feature_2',
       'premium_feature_3',
       'premium_feature_4',
       'premium_feature_5',
       'premium_feature_6',
       'premium_feature_7',
       'title_additional_plans',
       'desc_additional_plans',
       'additonal_plans_title_1',
       'additonal_plans_desc_1',
       'button_addtional_plans_text_1',
       'additonal_plans_title_2',
       'additonal_plans_desc_2',
       'button_addtional_plans_text_2',
       'additonal_plans_title_3',
       'additonal_plans_desc_3',
       'button_addtional_plans_text_3',
       'faq_section_title',
       'faq_title_1',
       'faq_desc_1',
       'faq_title_2',
       'faq_desc_2',
       'faq_title_3',
       'faq_desc_3',
       'faq_title_4',
       'faq_desc_4',
       'carousel_testimonial_1',
       'testiomonial_person_1',
       'carousel_info_1',
       'carousel_testimonial_2',
       'testiomonial_person_2',
       'carousel_info_2',
       'carousel_testimonial_3',
       'testiomonial_person_3',
       'carousel_info_3',
    ];
}
